-- MySQL Script generated by MySQL Workbench
-- 03/17/15 20:05:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `message` TEXT(500) NOT NULL,
  `done` TINYINT(1) NULL,
  `added` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faq` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` TEXT(100) NOT NULL,
  `answer` TEXT(500) NOT NULL,
  `order` INT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `symbole` VARCHAR(5) NOT NULL,
  `taux` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `devise_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `devise_id_idx` (`devise_id` ASC),
  CONSTRAINT `devise_id`
    FOREIGN KEY (`devise_id`)
    REFERENCES `mydb`.`devise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pays_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `pays_id_idx` (`pays_id` ASC),
  CONSTRAINT `pays_id`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `ville_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `birth` DATETIME NULL,
  `phone` VARCHAR(10) NOT NULL,
  `mobile` VARCHAR(10) NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id_idx` (`role_id` ASC),
  INDEX `ville_id_idx` (`ville_id` ASC),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ville_id`
    FOREIGN KEY (`ville_id`)
    REFERENCES `mydb`.`ville` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie_forum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sujets_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sujets_forum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_id` INT NOT NULL,
  `sujet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categorie_id_idx` (`categorie_id` ASC),
  CONSTRAINT `categorie_id`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `mydb`.`categorie_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message_forum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sujet_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `message` TEXT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `sujet_id_idx` (`sujet_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `sujet_id`
    FOREIGN KEY (`sujet_id`)
    REFERENCES `mydb`.`sujets_forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit_categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit_marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit_marque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_id` INT NOT NULL,
  `marque_id` INT NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `categorie_id_idx` (`categorie_id` ASC),
  INDEX `marque_id_idx` (`marque_id` ASC),
  CONSTRAINT `categorie_id`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `mydb`.`produit_categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `marque_id`
    FOREIGN KEY (`marque_id`)
    REFERENCES `mydb`.`produit_marque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `chemin` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `default` TINYINT(1) NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `produit_id_idx` (`produit_id` ASC),
  CONSTRAINT `produit_id`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posologie_sexe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posologie_sexe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `sexe` TINYINT(1) NOT NULL,
  `coeff` FLOAT NOT NULL,
  `added` VARCHAR(45) NOT NULL,
  `updated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `produit_id_idx` (`produit_id` ASC),
  CONSTRAINT `produit_id`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posologie_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posologie_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posologie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posologie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `min` FLOAT NOT NULL,
  `max` FLOAT NOT NULL,
  `coeff` FLOAT NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `produit_id_idx` (`produit_id` ASC),
  INDEX `type_id_idx` (`type_id` ASC),
  CONSTRAINT `produit_id`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`posologie_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fournisseur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `siret` VARCHAR(14) NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `contact` VARCHAR(45) NULL,
  `commentaire` TEXT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit_fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit_fournisseur` (
  `produit_id` INT NOT NULL,
  `fournisseur_id` INT NOT NULL,
  INDEX `produit_id_idx` (`produit_id` ASC),
  INDEX `fournisseur_id_idx` (`fournisseur_id` ASC),
  CONSTRAINT `produit_id`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fournisseur_id`
    FOREIGN KEY (`fournisseur_id`)
    REFERENCES `mydb`.`fournisseur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit_exemplaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit_exemplaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produit_id` INT NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produit_id_idx` (`produit_id` ASC),
  CONSTRAINT `produit_id`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`panier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`panier_exemplaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`panier_exemplaire` (
  `panier_id` INT NOT NULL,
  `exemplaire_id` INT NOT NULL,
  `qte` INT NOT NULL DEFAULT 1,
  `added` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  INDEX `panier_id_idx` (`panier_id` ASC),
  INDEX `exemplaire_id_idx` (`exemplaire_id` ASC),
  CONSTRAINT `panier_id`
    FOREIGN KEY (`panier_id`)
    REFERENCES `mydb`.`panier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exemplaire_id`
    FOREIGN KEY (`exemplaire_id`)
    REFERENCES `mydb`.`produit_exemplaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `devise_id` INT NOT NULL,
  `reference` VARCHAR(45) NULL,
  `commande_at` DATETIME NULL,
  `livraison_at` DATETIME NULL,
  `statut` VARCHAR(45) NULL,
  `montant` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `devise_id_idx` (`devise_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `devise_id`
    FOREIGN KEY (`devise_id`)
    REFERENCES `mydb`.`devise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande_exemplaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande_exemplaire` (
  `exemplaire_id` INT NOT NULL,
  `commande_id` INT NOT NULL,
  `devise_id` INT NOT NULL,
  `quantite` INT NULL,
  `montant` FLOAT NULL,
  PRIMARY KEY (`exemplaire_id`, `commande_id`),
  INDEX `commande_id_idx` (`commande_id` ASC),
  INDEX `devsie_id_idx` (`devise_id` ASC),
  CONSTRAINT `commande_id`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `exemplaire_id`
    FOREIGN KEY (`exemplaire_id`)
    REFERENCES `mydb`.`produit_exemplaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `devsie_id`
    FOREIGN KEY (`devise_id`)
    REFERENCES `mydb`.`devise` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande_paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande_paiement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commande_id` INT NOT NULL,
  `montant` FLOAT NOT NULL,
  `paiment_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `commande_id_idx` (`commande_id` ASC),
  CONSTRAINT `commande_id`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande_livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande_livraison` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commande_id` INT NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `deliver_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `commande_id_idx` (`commande_id` ASC),
  CONSTRAINT `commande_id`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`voip` (
  `user_id` INT NOT NULL,
  `operateur_id` INT NOT NULL,
  `durée` INT NULL,
  `encours` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`, `operateur_id`),
  INDEX `operateur_id_idx` (`operateur_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `operateur_id`
    FOREIGN KEY (`operateur_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
